default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: dpg-cticgb8gph6c7384rj10-a.oregon-postgres.render.com
  database: cad_db_e16s
  username: cad_db_e16s_user
  password: kKPfQADh7xhXMo2GBv7mI2qgm7JkbtHk

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
