:concurrency: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
:timeout: 25

:queues:
  - critical
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge

production:
  :concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY") { 10 } %>
